### ISSUE TITLE
🐛[BUG]: unable to install due to type error

### ISSUE THREAD

**Issue by mlopez-ntop** [NVIDIA/physicsnemo-sym#197]
### Version

1.7.0

### Describe the issue

When attempting to install the subprocess exits due to an error:
`TypeError: float() argument must be a string or a real number, not 'NoneType'`

This issue occurs when installing from pypi or from source

### Minimum reproducible example

To reproduce from source:
```
git clone git@github.com:NVIDIA/modulus-sym.git && cd modulus-sym

pip install --upgrade pip
pip install . 
```
### Relevant log output

```
(modulus-sym) C:\dev\modulus-sym>pip install .
Processing c:\dev\modulus-sym
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-igsxkvtb\overlay\Lib\site-packages\torch\_subclasses\functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "C:\Users\<user_name>\miniconda3\envs\modulus-sym\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\<user_name>\miniconda3\envs\modulus-sym\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\<user_name>\miniconda3\envs\modulus-sym\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-igsxkvtb\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-igsxkvtb\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-igsxkvtb\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 45, in <module>
        File "<string>", line 25, in cuda_extension
      TypeError: float() argument must be a string or a real number, not 'NoneType'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Environment details

Install was attempted on Windows 10 in a python virtual env (anaconda) with python version 3.11.2. Prior to installing both torch and numpy were manually installed via pip.
Additional attempts were made on a new virtual env using python 3.10.5 and outside of anaconda (python 3.10.5 as well)

**Comment by konok415** [comment]
Facing the same issue man ! Wish someone could help !

**Comment by eacuellarq** [comment]
you can try install WSL with Ubuntu distribution. According to page Nvidia Modulus sym, you have to use Linux always 

https://docs.nvidia.com/deeplearning/modulus/getting-started/

**Comment by AviAspen** [comment]
Can confirm works properly on wsl, only thing is your GPU driver should be updated and then update linux packages and install the cuda libraries for wsl from this [link](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=runfile_local). You may need to add the path as the instruction says after installing the coda drivers for wsl by doing export of the paths.

Check with `nvcc --version` and may have to restart wsl and do `source ~/.bashrc` if it doesn't work.

Once that is done install PyTorch and had to do the following 

```
pip install nvidia-modulus 
pip install "pint==0.19.2" 
pip install nvidia-modulus.sym --no-build-isolation 
```

**Comment by AvisP** [comment]
Can confirm works properly on wsl, only thing is your GPU driver should be updated and then update linux packages and install the cuda libraries for wsl from this [link](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=runfile_local). You may need to add the path as the instruction says after installing the coda drivers for wsl by doing export of the paths.

Check with nvcc --version and may have to restart wsl and do source ~/.bashrc if it doesn't work.

Once that is done install PyTorch and had to do the following

```
pip install nvidia-modulus 
pip install "pint==0.19.2" 
pip install nvidia-modulus.sym --no-build-isolation
```

**Comment by ktangsali** [comment]
Hi @mlopez-ntop do you still encounter this issue? Can you please try the latest builds/main?

**Comment by ktangsali** [comment]
Closing as no new updates. Please follow the instructions [here](https://github.com/NVIDIA/physicsnemo-sym?tab=readme-ov-file#installation) for installation guidance. 

Please re-open if the issue persists.
